apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testingress
  labels:
    name: testingress
  annotations:
    yarp.ingress.kubernetes.io/affinity: RandomPod
    kubernetes.io/ingress.class: yarp
spec:
  rules:
  - host: ufo.localtest.me
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: nginx
            port: 
              number: 80
